Task_2_1_1
Maksim-Kotenkov/OOP pull request #10
Opened 2024-02-04 08:09 UTC by Maksim-Kotenkov

2024-02-16 15:56 UTC, Maksim-Kotenkov commented
На приложенном изображении Linear лежит на оси размера массива, тк он выдавал очень большие цифры времени высиления и растягивал график вверх (было вообще не видно разницу между др линиями), поэтому я сделал возможным пропускать испытания линейного алгоритма.

2024-02-21 17:38 UTC, shadrina commented
Надо было тогда вообще отказаться от этого рисовальщика, если он не может нарисовать, как того требует задача. Ну это уже ладно. Почему `parallelStream()` так хило отработал?

2024-02-21 18:44 UTC, shadrina requested changes

2024-02-21 18:44 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/kotenkov/prime/ThreadWithReturn.java
> +            }
Когда ответ найден, всем остальным потокам можно сообщить о том, что работу можно заканчивать. Поработай с interrupt'ами.

2024-02-21 18:44 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/kotenkov/prime/PrimeChecker.java
> +        return result.stream().anyMatch(Boolean.FALSE::equals);
Вот собственно причина проседания parallelStream. 

```
 targetList.parallelStream().anyMatch(elem -> !prime(elem));
```

2024-02-21 18:44 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/kotenkov/prime/PrimeChecker.java
> +public class PrimeChecker {
Код этого класса в Си-стайл. Так как у нас ООП, тут напрашивается три реализации одного интерфейса.

2024-02-21 18:44 UTC, shadrina commented on Task_2_1_1/src/main/java/ru/nsu/kotenkov/prime/PrimeChecker.java
> +        return result.stream().anyMatch(Boolean.FALSE::equals);
Из-за `forEach()` он не останавливается, когда ответ уже найден.

2024-02-22 03:27 UTC, Maksim-Kotenkov commented
> Надо было тогда вообще отказаться от этого рисовальщика, если он не может нарисовать, как того требует задача. Ну это уже ладно.

Выяснил, что так плохо всё видно на изображении из-за высокого разрешения картинки + я забыл применить renderer к изображению, которое сохраняю. То есть при отображении графика программой всё было круто, а при сохранении ни цвета, ни толщина линий не кастомизировалась.

2024-03-07 15:18 UTC, shadrina approved these changes

2024-03-08 08:32 UTC, merged