Task_2_2_1
Maksim-Kotenkov/OOP pull request #11
Opened 2024-03-06 12:50 UTC by Maksim-Kotenkov

2024-03-07 15:42 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/Main.java
> +        }
Я лично люблю, когда main() as simple as possible. Вынесла бы вот это куда-то в отдельный метод. 

На твое усмотрение.

2024-03-07 15:42 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/Bakery.java
> +        System.out.println("OFFICE: Bakery opened");
В этой лабе вы вполне можете познакомиться с популярными библиотеками для логгирования. Например, log4j. Опять же, это необязательно, но будет полезно.

2024-03-07 15:42 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/kitchen/BakerThread.java
> +    private Thread myself;
А чем это отличается от `this`?

2024-03-07 15:42 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/management/Storage.java
> +    private AtomicInteger freeSpace;
Это по сути потокобезопасный контейнер, в этой задаче вам нужно самостоятельно осуществлять всю синхронизацию.

2024-03-07 15:42 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/management/Storage.java
> +    private ArrayList<Order> storage;
По сути не защищена от одновременного доступа

2024-03-08 08:43 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/Bakery.java
> +        System.out.println("OFFICE: Bakery opened");
Мне недавно из другой группы человек тоже сказал, что использовать System.out - такое себе. Не уверен, что в этой лабе всё успею перевести на нормальное логирование, но следующие уже точно.

2024-03-08 08:50 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/kitchen/BakerThread.java
> +    private Thread myself;
Если я буду в KitchenManager/DeliveryManager запускать прям объекты BakerThread, то после одного исполнения эти объекты больше нельзя будет запустить (ошибка о некорректном состоянии треда + прочитал, что треды по нескольку раз запускать невозможно). Как выход из этой ситуации - каждый раз, когда я хочу, чтобы работник начал что-то делать, я создаю new Thread(readyBakerThread или readyCourierThread), а работнику задаю этот вот myself = этому треду.

2024-03-10 06:05 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/management/Storage.java
> +    private AtomicInteger freeSpace;
Переработал

2024-03-10 06:05 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/management/Storage.java
> +    private ArrayList<Order> storage;
Переработал

2024-03-10 06:49 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/Main.java
> +        }
Внес в отдельный метод всё же, тк прикручивал ещё заказы с предыдущих дней

2024-03-11 06:06 UTC, Maksim-Kotenkov commented
Class diagram можно нормально посмотреть, если открывать изображение в новой вкладке.

2024-03-14 11:01 UTC, shadrina requested changes

2024-03-14 11:01 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/management/Storage.java
> +    private boolean interacting = false;
Готовый механизм синхронизации гарантирует корректность. А в данном случае без тайного знания о волшебном флаге этот класс невозможно использовать корректно.

2024-03-14 11:01 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/management/Storage.java
> +    private boolean interacting = false;
Как уже написала выше, посмотри реализацию BlockingQueue и код станет меньше и красивее.

2024-03-14 11:02 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/Bakery.java
> +        Thread kitchenThread = new Thread(this.kitchen);
В данном случае я не вижу, чтобы он где-то joinился и переиспользовался, как это сейчас работает для поваров и курьеров.

2024-03-14 11:21 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/Bakery.java
> +            System.err.println("OFFICE: Kitchen thread was interrupted during the work");
Да, скопировал и не поправил

2024-03-14 11:27 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/kitchen/KitchenManager.java
> +        }
Ладно, понял, нужно оставить одну ключевую точку для синхронизации - склад, который будет пассивно всех вокруг себя синхронизовать (чисто notify а все остальные на нём синхронизуются). Я правильно понял?

2024-03-14 11:34 UTC, Maksim-Kotenkov commented on Task_2_2_1/src/main/java/ru/nsu/kotenkov/bakery/staff/kitchen/KitchenManager.java
> +        }
А, перечитал снова, только переделать низшие сущности

2024-03-22 06:03 UTC, shadrina approved these changes

2024-03-22 06:04 UTC, merged