Task_1_2_1
Maksim-Kotenkov/OOP pull request #4
Opened 2023-10-07 12:04 UTC by Maksim-Kotenkov

2023-10-16 10:21 UTC, shadrina requested changes

2023-10-16 10:21 UTC, shadrina commented on Task_1_2_1/build.sh
> +javadoc -d build/docs/javadoc -sourcepath src/main/java -subpackages ru.nsu.kotenkov.tree
С предыдущей лабы делать "ручные" скрипты не надо. Вам было дано такое задание, чтобы просто прочувствовать, что делает gradle под капотом (в простейшем приближении).

Ну а если просто очень хочется, можно делать это локально и не коммитить в репозиторий.

2023-10-16 10:21 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/ManifestAddition.mf
> +Main-Class: ru.nsu.kotenkov.tree.Tree
Здесь нам это не надо =)

2023-10-16 10:21 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/Tree.java
> +        return (this.hashCode() == o.hashCode());
Скобочки лишние

2023-10-16 10:21 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/Tree.java
> +        }
А родитель специально считается при сравнении нод? 
Я просто на всякий случай уточню, что необязательно все поля класса должны участвовать при сравнении. Если так задумано, то хорошо. Просто по моей логике два поддерева могут быть равны, даже если прицеплены к разным родителям.

2023-10-16 10:21 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/TreeIterator.java
> +public class TreeIterator<T> implements Iterator<T> {
Обычно итераторы делают вложенными классами той коллекции, по которой они осуществляют итерацию. Они логически привязаны к этой конкретной коллекции. Это тоже интрумент инкапсуляции.

2023-10-16 10:21 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/TreeIterator.java
> +public class TreeIterator<T> implements Iterator<T> {
Тут получается публикация элемента внутренней реализации (сам класс `TreeIterator`).

2023-10-16 10:21 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/TreeIterator.java
> +        nodeList.addAll(creation(node));
Ну и посмотри, что я тебе на почту написала.

2023-10-16 10:28 UTC, Maksim-Kotenkov commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/Tree.java
> +        }
Вообще, да, вроде как логично про равенство двух поддеревьев у разных родителей... Просто в моменте я подумал их тоже считать. Будет логичнее не сравнивать родителей, да.

2023-10-16 10:30 UTC, Maksim-Kotenkov commented on Task_1_2_1/build.sh
> +javadoc -d build/docs/javadoc -sourcepath src/main/java -subpackages ru.nsu.kotenkov.tree
Хорошо) Зато разобрался с jar-никами и манифестами

2023-10-16 10:44 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/Tree.java
> +        }
Не забудь это поправить и в equals, и в hashCode

2023-10-16 10:44 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/TreeIterator.java
> +public class TreeIterator<T> implements Iterator<T> {
Другой способ сокрытия -- просто убрать public и сделать класс package-private

2023-10-16 12:18 UTC, Maksim-Kotenkov commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/TreeIterator.java
> +        nodeList.addAll(creation(node));
сделал

2023-10-28 09:50 UTC, shadrina approved these changes

2023-10-28 09:50 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/kotenkov/tree/Tree.java
> +import java.util.*;
Отключи варнинг или зачищай PR. В следующем не приму, так как было оговорено не раз.

2023-10-28 11:06 UTC, merged