Task_1_4_1
Maksim-Kotenkov/OOP pull request #7
Opened 2023-11-20 04:40 UTC by Maksim-Kotenkov

2023-11-28 08:23 UTC, shadrina requested changes

2023-11-28 08:23 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +    private final Map<Integer, Map<String, List<Mark>>> gradeBook;
Для вот таких больших типов лучше создавать отдельный класс с человеко-читаемым названием, а внутри него держать вот это (агрегацией). Это будет а-ля typealias

2023-11-28 08:23 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +            gradeBook.get(1).put(str, new ArrayList<>());
Может, сразу в переменную взять `gradeBook.get(1)`? Ты делаешь одно и то же `disciplines.size()` раз.

2023-11-28 08:23 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +    private final Map<Integer, Map<String, List<Mark>>> gradeBook;
Ну и сделать интуитивный API для работы с этой штукой. Чтобы не было `.get(MAGIC_CONSTANT).put(...)`

2023-11-28 08:23 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +                this.gradeBook.get(semester).get(discipline).add(mark);
Вот я о таких использованиях выше и говорю.

2023-11-28 08:23 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +        return res;
Stream API please

2023-11-28 08:23 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +public class GradeBook {
А как-то учитываются пересдачи и потеря стипендии из-за пересдачи?

2023-11-28 12:17 UTC, Maksim-Kotenkov commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +    private final Map<Integer, Map<String, List<Mark>>> gradeBook;
Done

2023-11-28 12:17 UTC, Maksim-Kotenkov commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +                this.gradeBook.get(semester).get(discipline).add(mark);
Пофиксилось новым классом

2023-11-28 13:02 UTC, Maksim-Kotenkov commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +public class GradeBook {
Неа, я смотрю только последнюю оценку по предмету в семестре. Могу щас сделать, чтоб там вылетала 2, если там не одна оценка -> была пересдача

2023-11-28 13:08 UTC, Maksim-Kotenkov commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +public class GradeBook {
Сделал

2023-11-28 13:11 UTC, Maksim-Kotenkov commented
Всё пофиксил + добавил поломку повышенной стипендии из-за пересдачи (по сути это двойка в сете оценок по дисциплине в семестре).
Большой метод для того, чтобы брать последние оценки по всем дисциплинам переделан в двустрочник с помощью Стрим Апи (getLastMarks).

2023-11-29 02:05 UTC, Maksim-Kotenkov commented
забыл тыкнуть запрос ревью после изменений

2023-12-05 04:05 UTC, shadrina approved these changes

2023-12-05 04:05 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kotenkov/gradebook/GradeBook.java
> +        NOPASS(0);
Если бы ты написал их ровно наоборот, это был бы ordinal, и val было бы избыточно.
Это не надо менять, это надо иметь в виду

2023-12-05 04:18 UTC, merged