Task_1_5_1
Maksim-Kotenkov/OOP pull request #8
Opened 2023-12-04 13:47 UTC by Maksim-Kotenkov

2023-12-12 08:58 UTC, shadrina requested changes

2023-12-12 08:58 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +            if (stackObj.getClass() == Double.class) {
```
if (stackObj instanceof Double dValue) {
    numStack.add(dValue);
}
```
Интроспекция + pattern matching

2023-12-12 08:58 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +                Operation currOperation = (Operation) stackObj;
Вообще по-хорошему сначала проверить инвариант `assert stackObj instanceof Operation;`

2023-12-12 08:58 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +                Operation currOperation = (Operation) stackObj;
Ассерты можно расставлять для себя и коллег, чтобы проверять инварианты. Это не способ общения с пользователем или обработки исключительных ситуаций, это для внутренних гарантий и проверок.

2023-12-12 08:58 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +        for (int ch = 0; ch < number.length(); ch++) {
Что-то мне подсказывает, что на стримах в одну строку это будет выглядеть более читаемо. Стоит попробовать.

2023-12-12 08:58 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Main.java
> +            }
Можно в System.err писать, а не в out.

2023-12-12 08:58 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Operation.java
> +    private double calcPlus(List<Double> args) {
Ты мог сделать один метод `calc(List<Double> args)` и переопределить его для каждой константы прямо наверху. Тогда можно было бы избавиться от метода `operationHandling()`.

2023-12-12 10:44 UTC, Maksim-Kotenkov commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +            if (stackObj.getClass() == Double.class) {
Выглядит интересно

2023-12-12 10:45 UTC, Maksim-Kotenkov commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +                Operation currOperation = (Operation) stackObj;
Справедливо... но просто у меня ничего кроме операций или даблов в стэке не планировалось, поэтому я пренебрег проверкой в этом месте. Но да, по хорошему, я тут кастую непонятно что, переделаю на предпроверку

2023-12-12 10:48 UTC, Maksim-Kotenkov commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Main.java
> +            }
Переделал

2023-12-12 11:09 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Operation.java
> +    private double calcPlus(List<Double> args) {
По сути это и есть то, что ты описываешь.

```
enum Op {
    ADD(2) {
        @Override
        protected double calc(List<Double> args) {
            // TODO: Arg checks
            return args.get(0) + args.get(1);
        }
    }, 
    SUB(2) {
        @Override
        protected double calc(List<Double> args) {
            // TODO: Arg checks
            return args.get(0) - args.get(1);
        }
    };

    int arity;

    Op(int arity) {
        this.arity = arity;
    }

    abstract double calc(List<Double> args);
}
```

2023-12-12 11:11 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +                Operation currOperation = (Operation) stackObj;
Идея там тоже должна высвечивать варнинг и предлагать ассерт

2023-12-12 11:38 UTC, Maksim-Kotenkov commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Operation.java
> +    private double calcPlus(List<Double> args) {
Вау, оно так работает... Круто, сделаю так)

2023-12-18 09:57 UTC, shadrina approved these changes
Хорошо

2023-12-18 09:57 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +import java.util.Stack;
Используйте `java.util.Deque`. `java.util.Stack` старый и синхронизованный.

2023-12-18 13:30 UTC, Maksim-Kotenkov commented on Task_1_5_1/src/main/java/ru/nsu/kotenkov/calculator/Calculator.java
> +import java.util.Stack;
Хорошо, дальше учту

2023-12-18 13:30 UTC, merged